#!/usr/bin/env bash
set -e

AUTH_FILE="$HOME/.airis/agent/auth.json"
AUTH_BACKUP="$HOME/.airis/agent/auth.json.bak"

# Restore auth.json on exit (success or failure)
cleanup() {
    if [[ -f "$AUTH_BACKUP" ]]; then
        mv "$AUTH_BACKUP" "$AUTH_FILE"
        echo "Restored auth.json"
    fi
}
trap cleanup EXIT

# Move auth.json out of the way
if [[ -f "$AUTH_FILE" ]]; then
    mv "$AUTH_FILE" "$AUTH_BACKUP"
    echo "Moved auth.json to backup"
fi

# Skip local LLM tests (ollama, lmstudio)
export AIRIS_NO_LOCAL_LLM=1

# Unset API keys (see packages/ai/src/stream.ts getEnvApiKey)
unset ANTHROPIC_AAIRIS_KEY
unset ANTHROPIC_OAUTH_TOKEN
unset OPENAI_AAIRIS_KEY
unset AZURE_OPENAI_AAIRIS_KEY
unset DEEPSEEK_AAIRIS_KEY
unset GEMINI_AAIRIS_KEY
unset GOOGLE_CLOUD_AAIRIS_KEY
unset GROQ_AAIRIS_KEY
unset CEREBRAS_AAIRIS_KEY
unset XAI_AAIRIS_KEY
unset OPENROUTER_AAIRIS_KEY
unset ZAI_AAIRIS_KEY
unset ZAI_CODING_CN_AAIRIS_KEY
unset MISTRAL_AAIRIS_KEY
unset MINIMAX_AAIRIS_KEY
unset MINIMAX_CN_AAIRIS_KEY
unset MOONSHOT_AAIRIS_KEY
unset KIMI_AAIRIS_KEY
unset HF_TOKEN
unset FIREWORKS_AAIRIS_KEY
unset TOGETHER_AAIRIS_KEY
unset AI_GATEWAY_AAIRIS_KEY
unset OPENCODE_AAIRIS_KEY
unset CLOUDFLARE_AAIRIS_KEY
unset CLOUDFLARE_ACCOUNT_ID
unset CLOUDFLARE_GATEWAY_ID
unset XIAOMI_AAIRIS_KEY
unset XIAOMI_TOKEN_PLAN_CN_AAIRIS_KEY
unset XIAOMI_TOKEN_PLAN_AMS_AAIRIS_KEY
unset XIAOMI_TOKEN_PLAN_SGP_AAIRIS_KEY
unset COPILOT_GITHUB_TOKEN
unset GH_TOKEN
unset GITHUB_TOKEN
unset GOOGLE_APPLICATION_CREDENTIALS
unset GOOGLE_CLOUD_PROJECT
unset GCLOUD_PROJECT
unset GOOGLE_CLOUD_LOCATION
unset AWS_PROFILE
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_REGION
unset AWS_DEFAULT_REGION
unset AWS_BEARER_TOKEN_BEDROCK
unset AWS_CONTAINER_CREDENTIALS_RELATIVE_URI
unset AWS_CONTAINER_CREDENTIALS_FULL_URI
unset AWS_WEB_IDENTITY_TOKEN_FILE
unset BEDROCK_EXTENSIVE_MODEL_TEST

echo "Running tests without API keys..."
npm test
